### ISSUE TITLE
Library doesn't update automatically even though library update frequency is set to daily

### ISSUE THREAD

**Issue by Mortus06** [CarlosEsco/Neko#1003]
### Steps to reproduce

Set library update frequency to "daily" and then, well, wait until the next day

### Expected behavior

The library updates automatically

### Actual behavior

I have to manually refresh the library

### Neko version

2.9.1.1

### Android version

Android 12, May 1st 2022 patch

### Device

Samsung S20 Ultra 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Try switching to a different update frequency for  a day or  two and switch back.  If not its possible the update job is getting killed by your device.

**Comment by CarlosEsco** [comment]
Can you also make sure you don't have library update only on wifi, if you do make sure you are on wifi when you run.

**Comment by Mortus06** [comment]
I have no restrictions enabled for library updates

**Comment by CarlosEsco** [comment]
Can you switch to the lowest frequency and see if it runs, and then switch back to daily after it runs and let me know? I wonder if i broke it during the migrations somehow.

**Comment by CarlosEsco** [comment]
Can you verify if you have this issue still.  You can check the stats page and see when the library update last started.

**Comment by Mortus06** [comment]
Checked the stats page and last library update shows N/A

I've been manually refreshing the library every now and then since I reported the issue

**Comment by CarlosEsco** [comment]
hmm, after a manual refresh it should show a timestamp on there

**Comment by Mortus06** [comment]
I updated it manually and it does show the timestamp. Still no auto update though, I tried switching the update frequency as well

**Comment by ohohohoo** [comment]
I'd like to chime in as well. I've been experiencing this issue since probably around 2/3 weeks ago but unlike the OP here, I have no issue at all until 2/3 weeks ago.

About probably a week ago (can't recall the exact time) the auto update work after I uninstalled Neko and reinstall and restore from backup. But it's not working right away after I restored the backup. I just fiddled with the settings (like switching the update time from 6 hours to manual and then switch to 12 hours and back to 6 again) and the day after it work.

But then 1 day after that or two I can't remember there's Neko updates and the auto update broke again.

**Comment by CarlosEsco** [comment]
Can you guys go through this site

https://dontkillmyapp.com/

**Comment by ohohohoo** [comment]
Actually I already did that since long ago (disabled the app sleeping or auto optimize app from Samsung, unrestricting background usage, etc) and everything was fine until 2 or 3 weeks ago as described in my post before. Also, actually I have tachiyomi installed too and it work and update just fine (library update every 12 hours). I use tachiyomi for anything other than Mangadex, while Neko is specifically for Mangadex.

**Comment by ohohohoo** [comment]
An update for my situation because right now the library auto update is working normally for me. As for what I did, since my last post here I tried:

1. Clear data and then reconfigure Neko to not restore from backup and chose to retrieve list from Mangadex and then double checked battery optimization disabled and set update to 6 hours and later 12 hours. It's not worked. 
2. Clear data and uninstalled just to make sure and reinstall Neko but this time recover data from backup also logged in to mangadex and only change update to 6 hours and disable battery optimization just to test. It worked, library auto update normally. Then I created 3 categories (which is how I categorized things before) where 1 is to download Manga in the category, another 1 for Manga that's already finished so it doesn't update that, and finally 1 is default category. Tested since yesterday with 6 hours update and it works fine. So far it has auto updated 3 times now.

**Comment by CarlosEsco** [comment]
So 2.10.10 I made some change namely.  Reverting the work manager library (main app and all other forks were using 2.6.0 and i was using 2.7.2).  On upgrading deleting existing library jobs, and readding.  Note: I noticed i was having the same library update issue.  Let me know if you still have issues @Mortus06.

**Comment by Mortus06** [comment]
Great, I've set the auto update frequency to 6 hours. Now I just have to wait

**Comment by Mortus06** [comment]
Update: it works! I've set the auto update frequency to daily now, that was my usual go-to, but I really think the problem is solved and I deeply thank you for always being available
