### ISSUE TITLE
Scroll loop on top of chapter list

### ISSUE THREAD

**Issue by D-Brox** [CarlosEsco/Neko#1516]
### Steps to reproduce

1. Open a title with a lot of chapters
2. Scroll down until the `Start reading Ch.xx` is no longer in vie
3. Scroll back up slowly

### Expected behavior

We can scroll up to the top regardless of speed

### Actual behavior

It gets stuck in a scroll loop, unless I scroll really fast.

### Neko version

2.13.5

### Android version

Android 13

### Device

Xiaomi Poco X4 Pro 5G

### Other details

https://media.discordapp.net/attachments/805199293358014524/1142802414462849024/2f2ugaYh.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by D-Brox** [comment]
https://github.com/CarlosEsco/Neko/assets/65723952/a2a649d2-c46e-48dc-8131-c8699ae84935

**Comment by D-Brox** [comment]
This only happens when there are unread chapters

**Comment by D-Brox** [comment]
https://github.com/CarlosEsco/Neko/assets/65723952/76ef4e4d-29de-4924-a9eb-1714b9af1e89

**Comment by CarlosEsco** [comment]
Known issue for a bit, surprised this isnt' a duplicate.  I'll take another look when i get free time to see if i can figure out why but my last attempts were unsuccessful.

**Comment by SilvVF** [comment]
This looks like it could be caused by something with Skydoves balloon compose library.

Leak Canary logs: https://pastebin.com/y6THHVuv 
[Balloon Popup window internal](https://github.com/skydoves/Balloon/blob/8691547c8b311c3b0d8d2efeb3919d73e2224678/balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt#L167)

The video below is with the current balloon implementation.

https://github.com/CarlosEsco/Neko/assets/98186105/051a9027-34d0-4ba5-9948-68552997c966

After removing the Balloon wrapper the issues with the jumping is not present anymore. 
I`m not sure why this happens but looking through the code for balloon it could be calculating its size after it is lazy loaded causing the jumping. Balloon is using AbstractComposeView to wrap what is provided inside of the content block then creating the popup based on that. The only thing with this theory is that it shouldn't happen when the content is not expanded like in the videos provided above unless it is also being caused by balloon being used for the search bar icons. Another note is i can recreate the bug with the list getting stuck everytime in the release version but only the jumping occurs in the debug build.

https://github.com/CarlosEsco/Neko/blob/7fde1feb0b18d45c7c518813946474fc3e2bb14e/app/src/main/java/org/nekomanga/presentation/screens/mangadetails/DescriptionBlock.kt#L412

`
        genres.forEach { genre ->
//            var balloonWindow: BalloonWindow? by remember { mutableStateOf(null) }
//
//            Balloon(
//                builder = toolTipBuilder(
//                    backgroundColor = MaterialTheme.colorScheme.surfaceColorAtElevationCustomColor(tagColor, 16.dp),
//                    dismissable = false
//                ),
//                balloonContent = {
//                    GenreBalloon(balloonWindow, genreSearch, genre, buttonColor, genreLibrarySearch)
//                },
//            ) { window ->
//
//                LaunchedEffect(Unit) {
//                    balloonWindow = window
//                }
                Chip(
                    label = genre,
                    containerColor = tagColor,
                    modifier = Modifier.clickable {
                        window.showAsDropDown()
                    },
                )
 //           }
        }
`

https://github.com/CarlosEsco/Neko/assets/98186105/78b21e5a-2056-4a7f-9f1b-61c0cf2b2019

**Comment by CarlosEsco** [comment]
> This looks like it could be caused by something with Skydoves balloon compose library.
> 
> Leak Canary logs: https://pastebin.com/y6THHVuv 
> [Balloon Popup window internal](https://github.com/skydoves/Balloon/blob/8691547c8b311c3b0d8d2efeb3919d73e2224678/balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt#L167)
> 
> The video below is with the current balloon implementation.
> 
> https://github.com/CarlosEsco/Neko/assets/98186105/051a9027-34d0-4ba5-9948-68552997c966
> 
> After removing the Balloon wrapper the issues with the jumping is not present anymore. 
> I`m not sure why this happens but looking through the code for balloon it could be calculating its size after it is lazy loaded causing the jumping. Balloon is using AbstractComposeView to wrap what is provided inside of the content block then creating the popup based on that. The only thing with this theory is that it shouldn't happen when the content is not expanded like in the videos provided above unless it is also being caused by balloon being used for the search bar icons. Another note is i can recreate the bug with the list getting stuck everytime in the release version but only the jumping occurs in the debug build.
> 
> https://github.com/CarlosEsco/Neko/blob/7fde1feb0b18d45c7c518813946474fc3e2bb14e/app/src/main/java/org/nekomanga/presentation/screens/mangadetails/DescriptionBlock.kt#L412
> 
> `
>         genres.forEach { genre ->
> //            var balloonWindow: BalloonWindow? by remember { mutableStateOf(null) }
> //
> //            Balloon(
> //                builder = toolTipBuilder(
> //                    backgroundColor = MaterialTheme.colorScheme.surfaceColorAtElevationCustomColor(tagColor, 16.dp),
> //                    dismissable = false
> //                ),
> //                balloonContent = {
> //                    GenreBalloon(balloonWindow, genreSearch, genre, buttonColor, genreLibrarySearch)
> //                },
> //            ) { window ->
> //
> //                LaunchedEffect(Unit) {
> //                    balloonWindow = window
> //                }
>                 Chip(
>                     label = genre,
>                     containerColor = tagColor,
>                     modifier = Modifier.clickable {
>                         window.showAsDropDown()
>                     },
>                 )
>  //           }
>         }
> `
> 
> https://github.com/CarlosEsco/Neko/assets/98186105/78b21e5a-2056-4a7f-9f1b-61c0cf2b2019
> 
> 

Oh thanks for helping dig into it!  Super helpful for the next release

**Comment by SilvVF** [comment]
@CarlosEsco did some testing without using the compose version and just using the builder then setting texts with setOnBalloonOverlayClickListener {  } in it. After the stutter is not present. Im not sure if you would be able to recreate the current ui using these callbacks I dont see one which provides a position of the click event to tell if it was a genre or library search.

**Comment by CarlosEsco** [comment]
> @CarlosEsco did some testing without using the compose version and just using the builder then setting texts with setOnBalloonOverlayClickListener {  } in it. After the stutter is not present. Im not sure if you would be able to recreate the current ui using these callbacks I dont see one which provides a position of the click event to tell if it was a genre or library search.

I can't remember what I'm using balloon for in that screen but I possibly can just remove it and do something else
