### ISSUE TITLE
[Bug] Next chapter is always the 2nd and is stuck

### ISSUE THREAD

**Issue by MisterJD91** [CarlosEsco/Neko#224]
### Device information
* Tachiyomi version: 2.0.13
* Android phone & version: Samsung Galaxy Tab S4 Android 9

## Steps to reproduce
1. Going into the next chapter

### Expected behavior
Start next chapter

### Actual behavior
Go into the 2nd chapter and become stuck at page 2

### Other details
When reading at the end of the selected chapter the reader goes into the 2nd ch of the manga even if it is the last chapter and than become stuck at the 2 page, the problem got solved deleting app data

**Comment by CarlosEsco** [comment]
If you ever get it to happen again a video would be helpful. With the enabled chapters filters and it happening

**Comment by Efreak** [comment]
Happening here too. I'll try to get a video and logcat later; my tablet isn't cooperating with the charger well today.

Version: current (just updated).  Device: Nexus 7, LineageOS 8/8.1 (don't recall which... It's the last official release. Will get details later).

More detail: it doesn't even try to open the next chapter. Between chapters, it says eg. previous chapter is volume 4 ch 22, next up is volume 1 chapter 2.

**Comment by CarlosEsco** [comment]
Enable the debug logging in advanced when you get the log cat

**Comment by Efreak** [comment]
I was unable to get a video, however there's nothing unusual about Neko--assuming chapter 2 is the next chapter.

More info: this does not happen when reading online, only when reading things that were downloaded ahead of time.

Logcat is [here](https://gist.githubusercontent.com/Efreak/246cee2ab441d7d65fc6c64f0887f1b1/raw/7db169f2f5197e862c7463dd0190fdad391969e7/Neko.txt), filtered to only show messages relating to Neko (logcat on my tablet is *very* spammy due to parts of Google services being disabled, and my phone is unrooted, unable to get logcat without my PC; let me know and I'll get a full logcat on my phone anyways)

**Comment by CarlosEsco** [comment]
What reader mode is this?  also are any filters enabled?

**Comment by VoraciousSergal** [comment]
Same errors.(downloaded chapters, goes to chapter 2, doesn't go past page 2)
Video: https://files.catbox.moe/7vue7k
![Screenshot_2020-06-23-01-40-48-529_tachiyomi mangadex](https://user-images.githubusercontent.com/67294914/85340467-3659d480-b4f7-11ea-83ba-c8127bf8bfc2.jpg)
And filters

**Comment by CarlosEsco** [comment]
I will add some more logging for the next release.  I still can't pin this down

**Comment by CarlosEsco** [comment]
@Efreak can you update to the latest version and then send logs after you enable debug

**Comment by CarlosEsco** [comment]
do you still have this issue?

**Comment by JanesDiary** [comment]
Here is the cleanest [log file](https://github.com/CarlosEsco/Neko/files/5095462/2020-08-19-release.2.txt) I could get with the issue happening.

**Comment by JanesDiary** [comment]
New [log file](https://github.com/CarlosEsco/Neko/files/5103679/2020-08-20-release.txt) from 2.1.3.3. Pretty much the same deal as before. Loaded the oldest chapter, skipped through to the next one, ran into the issue, backed out, reloaded the same chapter, skipped through to the end, loops back to the same chapter.

**Comment by Efreak** [comment]
Apologies for delay, I've been reading offline at work lately. This issue has disappeared for me, but I'm keeping debug enabled just in case.

**Comment by CarlosEsco** [comment]
No problem I have it narrowed down to a code block so when it dex comes back online I can look into

**Comment by CarlosEsco** [comment]
If someone else has a manga i can test i can verify but @JanesDiary  I've tested with your manga from the logs i am unable to  to get the chapter to repeat.  Though this manga is also weird because it was the same oneshot 3 times.  So the order is all messed up  https://mangadex.org/api/manga/34306.  the way the api returns feb 1st 2019 entry is the newest chapter so if you so it will always go to the no next chapter. The dates on the chapter list kinda throw you for a loop.

**Comment by JanesDiary** [comment]
New [log file.txt](https://github.com/CarlosEsco/Neko/files/5184851/2020-09-07-release.txt) I got for this issue.

**Comment by JanesDiary** [comment]
Another clean [log file](https://github.com/CarlosEsco/Neko/files/5212268/2020-09-12-release.txt) with the issue present.

**Comment by CarlosEsco** [comment]
Hopefully is fixed in next release, let me know

**Comment by CarlosEsco** [comment]
Any issues with latest release?

**Comment by JanesDiary** [comment]
I have not run into any issues so far.
