### ISSUE TITLE
[Bug] Magadex manga status section not working.

### ISSUE THREAD

**Issue by Tigoreetur** [CarlosEsco/Neko#392]
### Device information
* Tachiyomi version: 2.1.5.2
* Android phone & version: Moto G5 & 8.1.0

## Steps to reproduce
1. Change the status in the magadex manga status section. ex (from reading to on hold)
2. Refresh/Update the page

### Expected behavior
It sould display the changes made.

### Actual behavior
The chages haven't ben applied.

### Other details
Read chapter dosen't update either.

**Comment by CarlosEsco** [comment]
read chapter as in the mdlist chapter?  or as in marking the chapter read on the website?

Also are you making sure the loading symbol is stopped after changing a status, before shutting the sheet and refreshing?

**Comment by Tigoreetur** [comment]
If you set the read chapter nr. manually and wait till the loading circle goes away and update the page, it hasn't updated.

**Comment by Tigoreetur** [comment]
It doesn't get the changes from mdlist either. Not in a update or when clicking "Refresh tracking".

**Comment by CarlosEsco** [comment]
So there are two different issues.  THe chapter number not being updated correctly was an issue.  that is fixed in the next release.

changing follow status or chapter number then swipe refreshing in the manga page resetting.  Is a mangadex issue.  Their api server is caching the old result still.  If you go to the website it reflects what is correct.

**Comment by CarlosEsco** [comment]
Fixed chapter number issue in newest release
