### ISSUE TITLE
[Bug] Covers are pitch black for some manga.

### ISSUE THREAD

**Issue by Goretantath** [CarlosEsco/Neko#497]
I acknowledge that:

- I have updated to the latest version of the app.

---

### Device information
* Tachiyomi version: 2.4.2/2.4.1
* Android phone & version: Moto E (2020) Android 10

## Steps to reproduce
1. Open Library
2. See that most manga have pitch black covers.

### Expected behavior
Cover that was previously there should load.

### Actual behavior
Changed to pitch black cover instead of the uploaded cover/mangadex temp cover.

### Other details
This happend when I updated to 2.4.1 and I thought it'd fix itself in 2.4.2 . It hasn't and idk what to do..  I've refreshed every thing I can and toggled settings like the cache one and the port one to no avail. Thanks in advance! EDIT-forgot to mention befire update that all manga loaded their covers/mangadex temp cover.

**Comment by CarlosEsco** [comment]
this a dex DDOS Guard issue.  2.4.2 is using the temp covers for browse, but using the Dex api covers when in details.  The problem is DDOS guard is blocking requests to the image.  They have reached out to DDOS guard to figure out the issue.  Once something gets more stable the next release will be adjusted

**Comment by Goretantath** [comment]
Ah ok ty! I was wondering if it was on md's side.
