### ISSUE TITLE
Auto link Trackers

### ISSUE THREAD

**Issue by CarlosEsco** [CarlosEsco/Neko#53]
If user is logged in, when manga info is grabbed or selected auto link to the tracking site

**Comment by henrik9999** [comment]
I hope this will be done soon would make my life so much easier

**Comment by farahnur42** [comment]
+1 to this ^^

**Comment by Efreak** [comment]
Please make this optional per-tracker. In other words, under tracker settings, it should be possible to enable/disable automatically adding it.

Personally, while I think this would be useful, I'm satisfied with automatically adding the linked tracker entries instead of having to search for them.

**Comment by MaxEhrhart** [comment]
Thinking of one way of doing it, since there can be diverse names for the same manga, would be if, for example, 10 people or more than half of the users added a specific mal, anilist, or other track from one mangadex manga, auto add the tracking to that. That way it will auto-select to the related manga in the trackers. One slider option could enable this feature. It would be a great feature since there is almost 200 manga i'm reading

**Comment by henrik9999** [comment]
@MaxEhrhart this is not needed since mangadex has relation links on the manga

**Comment by CarlosEsco** [comment]
To add. I already am storing every id for each manga. So its really trying to cleanly auto track. Which is hard to do cause that code is a bit of a mess

**Comment by CarlosEsco** [comment]
In 2.10.0
