### ISSUE TITLE
I can't read new chapters

### ISSUE THREAD

**Issue by Giukia8x** [CarlosEsco/Neko#565]
I updated but the application doesn't work, I can't read new chapters

**Comment by CarlosEsco** [comment]
Can you provide more details?  Have you tried force closing the app?  Are you having this issue https://github.com/CarlosEsco/Neko/issues/521

**Comment by ajusa** [comment]
I'll provide all the details I can:
App was working fine until about 20 minutes ago for me, I installed it for the first time around 40 minutes ago. Read a few chapters, and now I can't seem to read any chapters. Additionally, deleting a title doesn't seem to do anything, and the filters don't seem to work either. This might be a different issue than the one that was posted here though.

I've tried force closing the app and I'm on 2.5.2. I've also tried clearing the chapter cache, which doesn't change anything. I haven't done any migration either (since this is the first time I'm using the app). Mangadex itself seems to be fine, up and running. There are errors in the log as well, attaching here:
[2021-07-08-release.txt](https://github.com/CarlosEsco/Neko/files/6785319/2021-07-08-release.txt)

**Comment by CarlosEsco** [comment]
@ajusa if you download the chapter, then read after its downloaded does it work?

**Comment by ajusa** [comment]
Hm, I tried downloading the chapter but it doesn't seem to do anything really. Nothing shows up in "Recents" either other than a huge refresh icon.

**Comment by CarlosEsco** [comment]
your issue definitely sounds like #521 though i don't know why a force close didnt work for you

**Comment by ajusa** [comment]
Yeah... happened again to me now. The only way I've found to get the app working again is to uninstall and reinstall it, which isn't really a sustainable operation as I need to resync and pull everything from Mangadex again. I can't figure out how/why it starts to freeze up though, it just happens with normal usage.

**Comment by Giukia8x** [comment]
So I have to uninstall and then install it again?
--
Inviato da Libero Mail per Android venerdì, 09 luglio 2021, 04:19PM +02:00 da Arham Jain  ***@***.*** :

**Comment by Giukia8x** [comment]
I migrated
--
Inviato da Libero Mail per Android venerdì, 09 luglio 2021, 04:19PM +02:00 da Arham Jain  ***@***.*** :

**Comment by CarlosEsco** [comment]
@Giukia8x you never provided any details or answers so you do you

**Comment by CarlosEsco** [comment]
closing in favor of #521 since they are more than likely the same issue

**Comment by Giukia8x** [comment]
Hello, 
I updated the application but the bug is still there :c
Sometimes it freezes and I can't read or see my updates. I can only uninstall and then install it again.
What can I do?
--
Inviato da Libero Mail per Android sabato, 10 luglio 2021, 01:46PM +02:00 da Carlos  ***@***.*** :
