### ISSUE TITLE
Bili Bili chapters fail to open

### ISSUE THREAD

**Issue by TheEd-itor** [CarlosEsco/Neko#872]
### Device information
* Neko version: 2.8.0.2
* Android phone & version: galaxy s21, android ver. 11

## Steps to reproduce
1. Find a manhua with chapters from bili bili comics
2. Select any chapter from the manhua
### Expected behavior
- Chapter loads normally
### Actual behavior
"Error getting image http code: 404"
### Other details
Wasn't an issue before the 2.8.0.2 update.

**Comment by CarlosEsco** [comment]
2.10.0 added a better error when this occurs. It's usually cause it's a paid chapter and bilibili sucks

**Comment by nobile01** [comment]
Device info:
- Version 2.10.0.1
- Android 12, Google Pixel 6 Pro
Expected behaviour:
Bilibili chapters that can open on mangadex website open on Neko as well 
Actual behaviour:
Chapters are available to open free on mangadex website but won't open through Neko, gives error saying it's unavailable, requires reading and/or purchasing on Bilibili
![Screenshot_20220821-193820](https://user-images.githubusercontent.com/111714391/185819199-1dfba07b-21fd-45a7-851d-81e70fa8857f.png)
![Screenshot_20220821-193840](https://user-images.githubusercontent.com/111714391/185819202-3e1f6971-9b99-4979-8c68-a398a8e159ad.png)
![Screenshot_20220821-193849](https://user-images.githubusercontent.com/111714391/185819204-597692cf-66ac-4c5a-841e-2673f0ceaba1.png)
